export const initialState = {
  estaConstruyendo: false,
  rosaSeleccionado: false,
  posicionSeleccionada: -1,
  baraja: [
    'madera',
    'ladrillo',
    'trigo',
    'piedra',
    'vidrio',
    'madera',
    'ladrillo',
    'trigo',
    'piedra',
    'vidrio',
    'madera',
    'ladrillo',
    'trigo',
    'piedra',
    'vidrio',
  ],
  materialSeleccionado: '',
  edificiosJugables: [],
  cottage: {
    name: 'cottage',
    description: '',
    image: '',
    icons: '',
    color: 'neutro',
    materiales: ['trigo', 'ladrillo', 'vidrio'],
  },
  naranja: [
    {
      name: 'abbey',
      color: 'naranja',
      description: '',
    },
    {
      name: 'chapel',
      color: 'naranja',
      description: '',
    },
    {
      name: 'cloister',
      color: 'naranja',
      description: '',
    },
    {
      name: 'temple',
      color: 'naranja',
      description: '',
    },
  ],
  rojo: [
    {
      name: 'farm',
      color: 'rojo',
      description: '',
    },
    {
      name: 'granary',
      color: 'rojo',
      description: '',
    },
    {
      name: 'greenhouse',
      color: 'rojo',
      description: '',
    },
    {
      name: 'orchard',
      color: 'rojo',
      description: '',
    },
  ],
  verde: [
    {
      name: 'almshouse',
      color: 'verde',
    },
    {
      name: 'feast hall',
      color: 'verde',
    },
    {
      name: 'inn',
      color: 'verde',
    },
    {
      name: 'tavern',
      color: 'verde',
    },
  ],
  gris: [
    {
      name: 'fountain',
      color: 'gris',
    },
    {
      name: 'millstone',
      color: 'gris',
    },
    {
      name: 'shed',
      color: 'gris',
    },
    {
      name: 'well',
      color: 'gris',
    },
  ],
  amarillo: [
    {
      name: 'bakery',
      color: 'amarillo',
    },
    {
      name: 'market',
      color: 'amarillo',
    },
    {
      color: 'amarillo',
      name: 'tailor',
    },
    {
      name: 'theater',
      color: 'amarillo',
    },
  ],
  azul: [
    {
      name: 'bank',
      color: 'azul',
    },
    {
      name: 'factory',
      color: 'azul',
    },
    {
      name: 'trading post',
      color: 'azul',
    },

    {
      name: 'warehouse',
      color: 'azul',
    },
  ],
  rosa: [
    {
      name: 'architect´s guild',
      color: 'rosa',
    },
    {
      name: 'archive of the second age',
      color: 'rosa',
    },
    {
      name: 'barrett castle',
      color: 'rosa',
    },
    {
      name: 'cathedral of caterina',
      color: 'rosa',
    },
    {
      name: 'fort ironweed',
      color: 'rosa',
    },
    {
      name: 'grove university',
      color: 'rosa',
    },
    {
      name: 'mandras palace',
      color: 'rosa',
    },
    {
      name: 'opaleye´s watch',
      color: 'rosa',
    },
    {
      name: 'shirne of the elder tree',
      color: 'rosa',
    },
    {
      name: 'silva forum',
      color: 'rosa',
    },
    {
      name: 'the starloom',
      color: 'rosa',
    },
    {
      name: 'statue of the bondmaker',
      color: 'rosa',
    },
  ],
  tablero: [
    {
      material: false,
      build: false,
      item: '',
      left: null,
      right: null,
      top: null,
      bot: null,
      topRight: null,
      topLeft: null,
      botRight: null,
      botLeft: null,
      id: 0,
      construible: false,
    },
    {
      material: false,
      build: false,
      item: '',
      left: null,
      right: null,
      top: null,
      bot: null,
      topRight: null,
      topLeft: null,
      botRight: null,
      botLeft: null,
      id: 1,
      construible: false,
    },
    {
      material: false,
      build: false,
      item: '',
      left: null,
      right: null,
      top: null,
      bot: null,
      topRight: null,
      topLeft: null,
      botRight: null,
      botLeft: null,
      id: 2,
      construible: false,
    },
    {
      material: false,
      build: false,
      item: '',
      left: null,
      right: null,
      top: null,
      bot: null,
      topRight: null,
      topLeft: null,
      botRight: null,
      botLeft: null,
      id: 3,
      construible: false,
    },
    {
      material: false,
      build: false,
      item: '',
      left: null,
      right: null,
      top: null,
      bot: null,
      topRight: null,
      topLeft: null,
      botRight: null,
      botLeft: null,
      id: 4,
      construible: false,
    },
    {
      material: false,
      build: false,
      item: '',
      left: null,
      right: null,
      top: null,
      bot: null,
      topRight: null,
      topLeft: null,
      botRight: null,
      botLeft: null,
      id: 5,
      construible: false,
    },
    {
      material: false,
      build: false,
      item: '',
      left: null,
      right: null,
      top: null,
      bot: null,
      topRight: null,
      topLeft: null,
      botRight: null,
      botLeft: null,
      id: 6,
      construible: false,
    },
    {
      material: false,
      build: false,
      item: '',
      left: null,
      right: null,
      top: null,
      bot: null,
      topRight: null,
      topLeft: null,
      botRight: null,
      botLeft: null,
      id: 7,
      construible: false,
    },
    {
      material: false,
      build: false,
      item: '',
      left: null,
      right: null,
      top: null,
      bot: null,
      topRight: null,
      topLeft: null,
      botRight: null,
      botLeft: null,
      id: 8,
      construible: false,
    },
    {
      material: false,
      build: false,
      item: '',
      left: null,
      right: null,
      top: null,
      bot: null,
      topRight: null,
      topLeft: null,
      botRight: null,
      botLeft: null,
      id: 9,
      construible: false,
    },
    {
      material: false,
      build: false,
      item: '',
      left: null,
      right: null,
      top: null,
      bot: null,
      topRight: null,
      topLeft: null,
      botRight: null,
      botLeft: null,
      id: 10,
      construible: false,
    },
    {
      material: false,
      build: false,
      item: '',
      left: null,
      right: null,
      top: null,
      bot: null,
      topRight: null,
      topLeft: null,
      botRight: null,
      botLeft: null,
      id: 11,
      construible: false,
    },
    {
      material: false,
      build: false,
      item: '',
      left: null,
      right: null,
      top: null,
      bot: null,
      topRight: null,
      topLeft: null,
      botRight: null,
      botLeft: null,
      id: 12,
      construible: false,
    },
    {
      material: false,
      build: false,
      item: '',
      left: null,
      right: null,
      top: null,
      bot: null,
      topRight: null,
      topLeft: null,
      botRight: null,
      botLeft: null,
      id: 13,
      construible: false,
    },
    {
      material: false,
      build: false,
      item: '',
      left: null,
      right: null,
      top: null,
      bot: null,
      topRight: null,
      topLeft: null,
      botRight: null,
      botLeft: null,
      id: 14,
      construible: false,
    },
    {
      material: false,
      build: false,
      item: '',
      left: null,
      right: null,
      top: null,
      bot: null,
      topRight: null,
      topLeft: null,
      botRight: null,
      botLeft: null,
      id: 15,
      construible: false,
    },
  ],
};
