export const initialState = {
  rosaSeleccionado: false,
  posicionSeleccionada: -1,
  baraja: [
    'madera',
    'ladrillo',
    'trigo',
    'piedra',
    'vidrio',
    'madera',
    'ladrillo',
    'trigo',
    'piedra',
    'vidrio',
    'madera',
    'ladrillo',
    'trigo',
    'piedra',
    'vidrio',
  ],
  materialSeleccionado: '',
  edificiosJugables: [],
  cottage: { name: 'cottage', description: '', image: '', icons: '' },
  naranja: [
    {
      name: 'abbey',
    },
    {
      name: 'chapel',
    },
    {
      name: 'cloister',
    },
    {
      name: 'temple',
    },
  ],
  rojo: [
    {
      name: 'farm',
    },
    {
      name: 'granary',
    },
    {
      name: 'greenhouse',
    },
    {
      name: 'orchard',
    },
  ],
  verde: [
    {
      name: 'almshouse',
    },
    {
      name: 'feast hall',
    },
    {
      name: 'inn',
    },
    {
      name: 'tavern',
    },
  ],
  gris: [
    {
      name: 'fountain',
    },
    {
      name: 'millstone',
    },
    {
      name: 'shed',
    },
    {
      name: 'well',
    },
  ],
  amarillo: [
    {
      name: 'bakery',
    },
    {
      name: 'market',
    },
    {
      name: 'tailor',
    },
    {
      name: 'theater',
    },
  ],
  azul: [
    {
      name: 'bank',
    },
    {
      name: 'factory',
    },
    {
      name: 'trading post',
    },
    {
      name: 'warehouse',
    },
  ],
  rosa: [
    {
      name: 'architect´s guild',
    },
    {
      name: 'archive of the second age',
    },
    {
      name: 'barrett castle',
    },
    {
      name: 'cathedral of caterina',
    },
    {
      name: 'fort ironweed',
    },
    {
      name: 'grove university',
    },
    {
      name: 'mandras palace',
    },
    {
      name: 'opaleye´s watch',
    },
    {
      name: 'shirne of the elder tree',
    },
    {
      name: 'silva forum',
    },
    {
      name: 'the starloom',
    },
    {
      name: 'statue of the bondmaker',
    },
  ],
  tablero: [
    {
      material: false,
      build: false,
      item: '',
      left: null,
      right: null,
      top: null,
      bot: null,
      topRight: null,
      topLeft: null,
      botRight: null,
      botLeft: null,
      id: 0,
      construible: false,
    },
    {
      material: false,
      build: false,
      item: '',
      left: null,
      right: null,
      top: null,
      bot: null,
      topRight: null,
      topLeft: null,
      botRight: null,
      botLeft: null,
      id: 1,
      construible: false,
    },
    {
      material: false,
      build: false,
      item: '',
      left: null,
      right: null,
      top: null,
      bot: null,
      topRight: null,
      topLeft: null,
      botRight: null,
      botLeft: null,
      id: 2,
      construible: false,
    },
    {
      material: false,
      build: false,
      item: '',
      left: null,
      right: null,
      top: null,
      bot: null,
      topRight: null,
      topLeft: null,
      botRight: null,
      botLeft: null,
      id: 3,
      construible: false,
    },
    {
      material: false,
      build: false,
      item: '',
      left: null,
      right: null,
      top: null,
      bot: null,
      topRight: null,
      topLeft: null,
      botRight: null,
      botLeft: null,
      id: 4,
      construible: false,
    },
    {
      material: false,
      build: false,
      item: '',
      left: null,
      right: null,
      top: null,
      bot: null,
      topRight: null,
      topLeft: null,
      botRight: null,
      botLeft: null,
      id: 5,
      construible: false,
    },
    {
      material: false,
      build: false,
      item: '',
      left: null,
      right: null,
      top: null,
      bot: null,
      topRight: null,
      topLeft: null,
      botRight: null,
      botLeft: null,
      id: 6,
      construible: false,
    },
    {
      material: false,
      build: false,
      item: '',
      left: null,
      right: null,
      top: null,
      bot: null,
      topRight: null,
      topLeft: null,
      botRight: null,
      botLeft: null,
      id: 7,
      construible: false,
    },
    {
      material: false,
      build: false,
      item: '',
      left: null,
      right: null,
      top: null,
      bot: null,
      topRight: null,
      topLeft: null,
      botRight: null,
      botLeft: null,
      id: 8,
      construible: false,
    },
    {
      material: false,
      build: false,
      item: '',
      left: null,
      right: null,
      top: null,
      bot: null,
      topRight: null,
      topLeft: null,
      botRight: null,
      botLeft: null,
      id: 9,
      construible: false,
    },
    {
      material: false,
      build: false,
      item: '',
      left: null,
      right: null,
      top: null,
      bot: null,
      topRight: null,
      topLeft: null,
      botRight: null,
      botLeft: null,
      id: 10,
      construible: false,
    },
    {
      material: false,
      build: false,
      item: '',
      left: null,
      right: null,
      top: null,
      bot: null,
      topRight: null,
      topLeft: null,
      botRight: null,
      botLeft: null,
      id: 11,
      construible: false,
    },
    {
      material: false,
      build: false,
      item: '',
      left: null,
      right: null,
      top: null,
      bot: null,
      topRight: null,
      topLeft: null,
      botRight: null,
      botLeft: null,
      id: 12,
      construible: false,
    },
    {
      material: false,
      build: false,
      item: '',
      left: null,
      right: null,
      top: null,
      bot: null,
      topRight: null,
      topLeft: null,
      botRight: null,
      botLeft: null,
      id: 13,
      construible: false,
    },
    {
      material: false,
      build: false,
      item: '',
      left: null,
      right: null,
      top: null,
      bot: null,
      topRight: null,
      topLeft: null,
      botRight: null,
      botLeft: null,
      id: 14,
      construible: false,
    },
    {
      material: false,
      build: false,
      item: '',
      left: null,
      right: null,
      top: null,
      bot: null,
      topRight: null,
      topLeft: null,
      botRight: null,
      botLeft: null,
      id: 15,
      construible: false,
    },
  ],
};
